export const PRINT_KEY_MAPPING: { [key: string]: string } = {
  /*------------ Staff Aloocation Report ------------*/
  campName: 'campName',
  campTypeName: 'campTypeName',
  location: 'location',
  campDuration: 'campDuration',
  vehicleNo: 'vehicleNo',

  expectedDonors: 'expectedDonors',
  distance: 'distance',
  address: 'address',
  type: 'type',
  lighting: 'lighting',
  communication: 'communication',
  electricSupply: 'electricSupply',
  handwashing: 'handwashing',
  fireSafety: 'fireSafety',
  otherFacilities: 'otherFacilities',
  furnitureAvailable: 'furnitureAvailable',
  wasteDisposal: 'wasteDisposal',
  medicalFacility: 'medicalFacility',
  remark: 'remark',
  dateTime: 'dateTime',
  equipmentItems: 'equipmentItems',
  teamMembers: 'teamMembers',
  cdoRemark: 'cdoRemark',
  startDateTime: 'startDateTime',
  vehicle: 'vehicle',
  organizerName: 'organizerName',
  unitsCollected: 'unitsCollected',
  endDateTime: 'endDateTime',
  mobile: 'mobile',
  organizationType: 'organizationType',
  bagsToCollect: 'bagsToCollect',

  approvedRemarks: 'approvedRemarks',
  inspectionTypeName: 'inspectionTypeName',
  bagCollectionCount: 'bagCollectionCount',
  probableDonor: 'probableDonor',
  distanceFromCenter: 'distanceFromCenter',
  campStartDate: 'campStartDate',
  campEndDate: 'campEndDate',

  /*----------------------------------------------
        Key Mapping for Donor-Screening PDF
  ----------------------------------------------*/
  firstName: 'firstName',
  middleName: 'middleName',
  familyName: 'familyName',
  gender: 'gender',
  dateOfBirth: 'dateOfBirth',
  bagNo: 'bagNo',
  statusDateTime: 'statusDateTime',
  citizenCode: 'citizenCode',
  donorCode: 'donorCode',
  address1: 'address1',
  address2: 'address2',
  areaName: 'areaName',
  cityName: 'cityName',
  donationType: 'donationType',
  scannerURL: 'scannerURL',
  eventType: 'eventType',
  bloodComponentName: 'bloodComponentName',
  emailAddress: 'emailAddress',
  contactDetails: 'contactDetails',
  occupation: 'occupation',
  identityName: 'identityName',
  identityNumber: 'identityNumber',
  pincode: 'pincode',
  stateName: 'stateName',
  countryName: 'countryName',
  donatedEarlier: 'donatedEarlier',
  dateOfLastDonation: 'dateOfLastDonation',
  bloodGroup: 'bloodGroup',
  donationStatus: 'donationStatus',
  donorConsent: 'donorConsent',
};
