import { Component } from '@angular/core';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import autoTable from 'jspdf-autotable';

@Component({
    selector: 'app-table-to-pdf',
    imports: [],
    templateUrl: './table-to-pdf.component.html',
    styleUrl: './table-to-pdf.component.scss'
})
export class TableToPdfComponent {
  // Sample dynamic data for the table
  tableData = [
    {
      id: 1,
      name: 'Dolo 500mg LSCS (Lower Segment Cesarean Section) CSSD LSCS (Lower Segment Cesarean Section) CSSD',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
    {
      id: 1,
      name: 'Dolo 500mg',
      '12AM': 'A',
      '1AM': 'A',
      '2AM': 'A',
      '3AM': 'A',
      '4AM': 'A',
      '5AM': 'A',
      '6AM': 'A',
      '7AM': 'A',
      '8AM': 'A',
      '9AM': 'A',
      '10AM': 'A',
      '11AM': 'A',
      '12PM': 'A',
      '1PM': 'A',
      '2PM': 'A',
      '3PM': 'A',
      '4PM': 'A',
      '5PM': 'A',
      '6PM': 'A',
      '7PM': 'A',
      '8PM': 'A',
      '9PM': 'A',
      '10PM': 'A',
      '11PM': 'A',
    },
  ];

  // generatePDF() {
  //   const doc = new jsPDF();
  //   // Function to add the header on every page
  //   const addHeader = (doc: jsPDF) => {
  //     doc.setFontSize(12);
  //     doc.text('My Custom Header', doc.internal.pageSize.width / 2, 15, {
  //       align: 'center',
  //     });
  //   };
  //   // Function to add the footer on every page
  //   const addFooter = (doc: jsPDF) => {
  //     const pageCount = doc.getNumberOfPages(); // Get total number of pages
  //     for (let i = 1; i <= pageCount; i++) {
  //       doc.setPage(i);
  //       const pageHeight = doc.internal.pageSize.height;
  //       doc.setFontSize(8);
  //       doc.text(
  //         `Page ${i} of ${pageCount}`,
  //         doc.internal.pageSize.width - 30,
  //         pageHeight - 10
  //       );
  //       doc.text('My PDF Footer', 14, pageHeight - 10);
  //     }
  //   };
  //   // Generate table with headers
  //   autoTable(doc, {
  //     head: [['ID', 'Name', 'Age', 'Address']],
  //     body: this.tableData.map((item) => [
  //       item.id,
  //       item.name,
  //       item.age,
  //       item.address,
  //     ]),
  //     startY: 30, // Space below header
  //     margin: { top: 20 },
  //     theme: 'grid',
  //     styles: {
  //       fontSize: 7, // 👈 Set the font size for table body
  //     },
  //     headStyles: {
  //       fontSize: 7, // 👈 Set font size for table headers
  //       fillColor: [100, 100, 100], // Optional: Change header background color
  //       textColor: 255, // White text color for header
  //     },
  //     didDrawPage: () => {
  //       addHeader(doc); // Add header to every page
  //     },
  //   });
  //   addFooter(doc); // Add footer to all pages
  //   doc.save('multi-page-table.pdf');
  // }

  generatePDF() {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    let marginTop = 30; // Space below header
    let marginBottom = 15; // Space above footer
    let startY = marginTop;

    // Capture Header
    const headerElement = document.getElementById('header');
    const footerElement = document.getElementById('footer');

    html2canvas(headerElement!, { scale: 2 }).then((headerCanvas) => {
      const headerImg = headerCanvas.toDataURL('image/png');

      html2canvas(footerElement!, { scale: 2 }).then((footerCanvas) => {
        const footerImg = footerCanvas.toDataURL('image/png');

        autoTable(doc, {
          head: [
            [
              'Events/Timing',
              '12AM',
              '1AM',
              '2AM',
              '3AM',
              '4AM',
              '5AM',
              '6AM',
              '7AM',
              '8AM',
              '9AM',
              '10AM',
              '11AM',
              '1PM',
              '2PM',
              '2PM',
              '3PM',
              '4PM',
              '5PM',
              '6PM',
              '7PM',
              '8PM',
              '9PM',
              '10PM',
              '11PM',
            ],
          ],
          body: [
            // ✅ Full-Width Row with Colspan
            [
              {
                content: 'Daily Schedule Overview',
                colSpan: 26,
                styles: {
                  halign: 'left', // Center text
                  fontStyle: 'bold', // Bold text
                  fillColor: [241, 245, 255], // Light Blue background
                  textColor: [0, 0, 0], // Black text
                  lineWidth: 0.1, // Border thickness
                  // lineColor: [0, 0, 0], // Black border
                },
              },
            ],

            // ✅ Table Data Rows
            ...this.tableData.map((item) => [
              item.name,
              item['12AM'],
              item['1AM'],
              item['2AM'],
              item['3AM'],
              item['4AM'],
              item['5AM'],
              item['6AM'],
              item['7AM'],
              item['8AM'],
              item['9AM'],
              item['10AM'],
              item['11AM'],
              item['12PM'],
              item['1PM'],
              item['2PM'],
              item['3PM'],
              item['4PM'],
              item['5PM'],
              item['6PM'],
              item['7PM'],
              item['8PM'],
              item['9PM'],
              item['10PM'],
              item['11PM'],
            ]),
          ],
          startY: startY,
          margin: { top: marginTop, bottom: marginBottom, left: 7, right: 7 }, // ✅ Remove Left & Right Space
          tableWidth: 'auto',
          theme: 'grid',
          styles: { fontSize: 6 },
          // ✅ Set Heading Styles
          headStyles: {
            fontSize: 6, // ✅ Custom Font Size
            fontStyle: 'bold', // ✅ Bold Font
            fillColor: [249, 250, 252], // ✅ Background Color
            textColor: 0, // ✅ Text Color (Black)
            lineWidth: 0.1, // ✅ Border Thickness
            cellPadding: [2, 0.4],
            // ✅ Set horizontal and vertical padding
            // cellPadding: [5, 10], // [vertical, horizontal]
            // OR
            // cellPadding: [5, 10, 5, 10], // [top, right, bottom, left]
          },

          columnStyles: {
            0: { cellWidth: 60 },
          },
          didParseCell: (data) => {
            // Change only the first cell padding
            if (data.section === 'head' && data.column.index === 0) {
              data.cell.styles.cellPadding = [2, 2]; // [vertical, horizontal]
            }
          },

          // ✅ Set First Column Width and Borders
          // columnStyles: {
          //   0: {
          //     cellWidth: 40, // ✅ Set Width for First Column
          //     fontStyle: 'bold', // ✅ Bold Font for First Column
          //     lineWidth: 0.5, // ✅ Border Thickness
          //     lineColor: [0, 0, 0], // ✅ Border Color
          //   },
          // },
          didDrawPage: (data) => {
            // Draw Header Image
            doc.addImage(headerImg, 'PNG', 8, 5, pageWidth - 15, 23);
            // Draw Footer Image
            doc.addImage(
              footerImg,
              'PNG',
              8,
              pageHeight - 12,
              pageWidth - 15,
              6
            );

            // Page Number
            doc.setFontSize(6);
            doc.text(
              `Page ${doc.getNumberOfPages()}`,
              pageWidth - 20,
              pageHeight - 8.2
            );

            // const totalPages = (doc.internal as any).getNumberOfPages(); // Get total pages
            // const currentPage = doc.internal.pages.length - 1; // Get current page number

            // doc.setFontSize(6);
            // // Ensure all pages display the same total page count
            // if (currentPage === totalPages) {
            //   for (let i = 1; i <= totalPages; i++) {
            //     doc.setPage(i);
            //     doc.text(
            //       `Page ${i} / ${totalPages}`,
            //       doc.internal.pageSize.width - 40,
            //       doc.internal.pageSize.height - 8.2
            //     );
            //   }
            // }
          },
        });

        doc.save('multi-page-table.pdf');
      });
    });
  }
}
